# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    secrets: inherit

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Decrypts config files
      run: npm run configure -- ${{ secrets.CONFIG_PASSPHRASE }}
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run linter
    # - name: Dispatch commands
      # run: npm run dispatch-test
    - name: Run tests
      run: npm test
    # - name: Undispatch commands
      # run: npm run undispatch-test
  
  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    concurrency:
      group: ONE_DEPLOY_ONLY
      cancel-in-progress: true
    secrets: inherit

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Decrypts config files
        run: npm run configure -- ${{ secrets.CONFIG_PASSPHRASE }}
      - name: Install pm2
        run: npm install pm2@latest -g
      - name: Deploy to backend using pm2
        run: npm run deploy -- ${{ secrets.CONFIG_PASSPHRASE }} >> /dev/null
      


