# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Decrypts config.json file
      run: npm run configure -- ${{ secrets.CONFIG_PASSPHRASE }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run linter
    - name: Dispatch commands
      run: npm run dispatch-test
    - name: Run tests
      run: npm test
    - name: Undispatch commands
      run: npm run undispatch-test
  
  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Decrypts config.json file
        run: npm run configure -- ${{ secrets.CONFIG_PASSPHRASE }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install pm2
        run: npm install pm2@latest -g
      - name: Deploy to backend using pm2
        run: pm2 deploy ./configs/ecosystem.config.js production ${{ secrets.CONFIG_PASSPHRASE }} >> /dev/null
      


